from adapters.registry import AdapterRegistry
from adapters.arithmetic_adapter import ArithmeticInputAdapter
from adapters.algebra_adapter import AlgebraInputAdapter
from adapters.calculus_adapter import CalculusInputAdapter
